version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "bun"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      semver-major-days: 14
